115 delete users
axoxelol1/dat257-hasse-andersson pull request #116
Opened 2022-05-17 00:34 UTC by MechaFlex

Builds upon #82 / #114 

The new route is /users where all users are listed. They can be deleted as well, but only by the admin.

2022-05-17 08:13 UTC, simonengstrm requested changes
Nice work! Maybe would be good if the navbar was on this page to enable the user to navigate back to the main site?

2022-05-17 08:16 UTC, MechaFlex commented
Yes, that's a good idea! Will look in to it!

2022-05-19 21:19 UTC, axoxelol1 approved these changes
lgtm

2022-05-19 21:21 UTC, simonengstrm approved these changes

2022-05-19 21:21 UTC, merged